---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: wireguard-config
  namespace: default
data:
  wireguard.conf: |
    [Interface]
    Address = 172.30.1.1/24
    ListenPort = 5555
    PrivateKey = PrIvAtE/KeY+SeRvEr==

    [Peer]
    PublicKey = PuBlIc/KeY+ClIeNt1==
    AllowedIPs = 10.0.0.2/32

    [Peer]
    PublicKey = PuBlIc/KeY+ClIeNt2==
    AllowedIPs = 10.0.0.3/32
