---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: my-custom-registry/wireguard:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: configuration
            mountPath: /etc/wireguard.conf
            subPath: wireguard.conf
        ports:
        - containerPort: 5555
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
#      imagePullSecrets:
#      - name: regcred
      volumes:
        - name: configuration
          configMap:
            name: wireguard-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wireguard
  name: wireguard
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5555
    nodePort: 32766
    protocol: UDP
    targetPort: 5555
  selector:
    app: wireguard
